### ISSUE TITLE
Dask Permission error on Amazon Binder

### ISSUE THREAD

**Issue by bonnland** [pangeo-data/pangeo-binder#150]
When trying to run this Binder session: https://hub.aws-uswest2-binder.pangeo.io/user/ncar-cesm-lens-aws-uvea1vit/lab

I am getting this error when trying to create a Dask cluster:
```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /srv/conda/envs/notebook/lib/python3.7/asyncio/tasks.py:623> exception=ApiException()>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/deploy/spec.py", line 50, in _
    await self.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_kubernetes/core.py", line 78, in start
    raise e
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_kubernetes/core.py", line 69, in start
    self.namespace, self.pod_template
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/kubernetes_asyncio/client/api_client.py", line 166, in __call_api
    _request_timeout=_request_timeout)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/kubernetes_asyncio/client/rest.py", line 230, in POST
    body=body))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/kubernetes_asyncio/client/rest.py", line 181, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: <CIMultiDictProxy('Audit-Id': '93439412-c66a-42b7-8069-c10509eadf62', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 04 May 2020 19:45:28 GMT', 'Content-Length': '277')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:prod:pangeo\" cannot create resource \"pods\" in API group \"\" in the namespace \"prod\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```
Is this a simple auth problem, or some other issue entirely?   If this is the wrong place to report the problem, apologies.

To reproduce the problem, click the following link and try running the kay-et-al-2015-v3.ipynb notebook:

https://aws-uswest2-binder.pangeo.io/v2/gh/NCAR/cesm-lens-aws/master?urlpath=lab

**Comment by scottyhq** [comment]
@bonnland - looks like cesm_lens is still using dask_kubernetes, we're in the process of moving people to dask_gateway for creating clusters (dask_kubernetes isn't going to work going forward b/c of configuration changes) It should be an easy transition for your notebook:

you have:
```python
# Create cluster
from dask_kubernetes import KubeCluster
from dask.distributed import Client
cluster = KubeCluster()
cluster.adapt(minimum=2, maximum=100, wait_count=60)
# Connect to cluster
client = Client(cluster)
# Display cluster dashboard URL
cluster
```

You need:
```python
from dask_gateway import Gateway
from dask.distributed import Client
gateway = Gateway()
cluster = gateway.new_cluster()
cluster.adapt(minimum=2, maximum=100)
client = Client(cluster)
cluster
```

example notebook:
http://gallery.pangeo.io/repos/TomAugspurger/pangeo-dask-gateway/using-dask-gateway.html

blog post:
https://medium.com/pangeo/pangeo-with-dask-gateway-4b638825f105 

**You'll also need to update your binder configuration to ensure you're using dask_gateway>0.7.1**
