### ISSUE TITLE
[DOC] Builds are failing

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-binder#97]
Latest example: https://readthedocs.org/projects/pangeo-binder/builds/10596649/

```
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done
Adding copy buttons to code blocks...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-binder/envs/staging/lib/python3.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-binder/envs/staging/lib/python3.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-binder/envs/staging/lib/python3.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-binder/envs/staging/lib/python3.7/site-packages/sphinx/registry.py", line 207, in load_extension
    metadata = mod.setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-binder/envs/staging/lib/python3.7/site-packages/sphinx_copybutton/__init__.py", line 25, in setup
    app.add_js_file('clipboard.min.js')
AttributeError: 'Sphinx' object has no attribute 'add_js_file'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pangeo-binder/envs/staging/lib/python3.7/site-packages/sphinx_copybutton/__init__.py", line 25, in setup
    app.add_js_file('clipboard.min.js')
AttributeError: 'Sphinx' object has no attribute 'add_js_file'
The full traceback has been saved in /tmp/sphinx-err-2doxmucw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by jhamman** [comment]
closed by #98. Thanks @TomAugspurger!
